#!/bin/bash
# ------------------------------------------------------------------------------
# fc_check - Check for string literal to block github merge into main.
#
# September 2022, Gurkiran Singh
#
# Copyright (c) 2022
# All rights reserved.
# ------------------------------------------------------------------------------

FC_STRING1="FAIL_"
FC_STRING2="COMMIT"
FC_STRING="$FC_STRING1$FC_STRING2"

RC_PASS=0
RC_FAIL=1
RC_ERROR=2

EXCLUDE_DIR=".git/"

CMD="grep -rni $FC_STRING --exclude-dir=$EXCLUDE_DIR"

OUTPUT="$($CMD)"
RC="$?"

if [ $RC -eq 0 ]; then # matching files found
    echo "$FC_STRING strings found. Please remove:"
    echo $OUTPUT
    RC=$RC_FAIL
elif [ $RC -eq 1 ]; then # matching files not found
    echo "No files found with '$FC_STRING'."
    RC=$RC_PASS
else
    echo "Error running bash command."
    echo "  Command ran: $CMD"
    echo "  Output: $OUTPUT"
    echo "  Return code $RC"
    RC=$RC_ERROR
fi

exit $RC
