#!/usr/bin/bash
# ------------------------------------------------------------------------------
# mypy - Type checking.
#
# December 2022, Gurkiran Singh
#
# Copyright (c) 2022
# All rights reserved.
# ------------------------------------------------------------------------------

python -m mypy . --disallow-untyped-defs --disallow-incomplete-defs --ignore-missing-imports

RC="$?"

exit $RC
