name: Autoformat

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Pull git workspace
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black
      - name: Analyse code with autoformat
        run: python tools/autoformat.py -v
