name: Fail commit string check

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Pull git workspace
        uses: actions/checkout@v3
      - name: Set permissions on script
        run: chmod u+x tools/fc_check
      - name: Check for fail commit strings
        run: tools/fc_check
