name: Push Checks

on: [push]

jobs:
  autoformat:
    name: Autoformat
    runs-on: ubuntu-latest
    steps:
      - name: Pull git workspace
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black
      - name: Analyse code with black
        run: python tools/autoformat.py -v
  branch-name:
    name: Branch name
    runs-on: ubuntu-latest
    steps:
      - name: Pull git workspace
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
      - name: Check branch name
        run: python tools/branch_name.py
  copyright:
    name: Copyright notice
    runs-on: ubuntu-latest
    steps:
      - name: Pull git workspace
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: Check formatting of copyright notices
        run: python tools/copyright.py
  fail-commit:
    name: FAIL_COMMIT
    runs-on: ubuntu-latest
    steps:
      - name: Pull git workspace
        uses: actions/checkout@v3
      - name: Check for fail commit strings
        run: tools/fc_check
  mypy:
    name: Mypy
    runs-on: ubuntu-latest
    steps:
      - name: Pull git workspace
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mypy
      - name: Check typing
        run: tools/mypy.py
  pylint:
    name: Pylint
    runs-on: ubuntu-latest
    steps:
    - name: Pull git workspace
      uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: 3.10
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install typing-extensions --upgrade
    - name: Analyse the code with pylint
      run: |
        python tools/lint.py
